config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  
  resources :posts
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  
  validates :title, presence: true, length: {maximum: 140}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new
      if @post.save(post_params)
        flash[:notice] = 'Successfully created post!'
        redirect_to post_path(@post)
      else
        flash[:alert] = 'Error creating new post!'
        render :new
      end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated post!'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Error updating post!'
      render :Edit
    end
  end
  
  def show
  end
  
  def destroy
    if @post.destroy
      flash[:notice] = 'Successfully deleted post!'
      redirect_to posts_path
    else
      flash[:alert] = 'Error updaing post!'
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body)
  end
  
  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.haml
.col-sm-offset-4.col-sm-4.col-xs-12
  - if controller_name != 'sessions'
    = link_to "Log in", new_session_path(resource_name)
    %br/
  - if devise_mapping.registerable? && controller_name != 'registrations'
    = link_to "Sign up", new_registration_path(resource_name)
    %br/
  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to "Forgot your password?", new_password_path(resource_name)
    %br/
  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
    %br/
  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
    %br/

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
      %br/

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "#"} Scotch Blog
  #navbar-collapse.collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      %li= link_to 'Home', root_path
      - if admin_signed_in?
        / This block is only visible to signed in admins
        %li= link_to 'New Post', new_post_path
        %li= link_to 'My Account', edit_admin_registration_path
        %li= link_to 'Logout', destroy_admin_session_path, :method => :delete
        / The block ends here
      - else
        %li= link_to 'Login', new_admin_session_path

app/views/layouts/application.html.haml
%html
  %head
    %title ScotchBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = render "layouts/navigation"
    %p.notice = notice
    %p.alert = alert
    .container-fluid
      = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li
            = msg
  .form-group
    = f.input :title, class: "form-control"
  .form-group
    = f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control"
  .form-group
    = f.button :submit

app/views/posts/edit.html.haml
%h2 Edit Post

= render "posts/form"

app/views/posts/index.html.haml
.container
  .col-sm-10.col-sm-offset-1.col-xs-12.blog-content
    - @posts.each do |post|
      .col-xs-12
        .text-center
          %h2= post.title
          %h6= post.created_at.strftime('%b %d, %Y')
        %div
          = raw(post.body).truncate(358)
        .text-center
          = link_to "READ MORE", post_path(post)
        - if admin_signed_in?
          = link_to "Show", post_path(post), class: "btn btn-primary"
          = link_to "Edit", edit_post_path(post), class: "btn btn-default"
          = link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete
        %hr/

app/views/posts/new.html.haml
%h2 Create New Post

= render 'posts/form'

app/views/posts/show.html.haml
%html
  .col-sm-11.col-xs-12.blog-content
    %h2.text-center
      = @post.title
    %h5.text-center
      = @post.created_at.strftime('%b %d, %Y')
    %div
      = raw @post.body